### ISSUE TITLE
Опечатки в лекции 7 (31.03)

### ISSUE THREAD

**Issue by glushenkovIG** [AShepelevv/mipt.diht.probability#25]
Опечатки в лекции 7

**Comment by glushenkovIG** [comment]
Индекс у интеграла в определении условной плотности должен быть B

b -> B

**fixed**

**Comment by glushenkovIG** [comment]
страница 22

**Comment by AShepelevv** [comment]
<img width="677" alt="screen shot 2018-06-07 at 16 29 32" src="https://user-images.githubusercontent.com/23651313/41102687-19387d80-6a70-11e8-8c79-912b406c3585.png">

- Модуль закрыть
- Лишняя точка
- \in -> =
- лишняя стрелочка

**fixed**

**Comment by valentiay** [comment]
Страница 21. Не закрыта скобка у матожидания
![image](https://user-images.githubusercontent.com/14908883/41104146-6b31a7f8-6a73-11e8-9a45-90d2a683dc95.png)

**fixed**

**Comment by valentiay** [comment]
Страница 22. Только только
![image](https://user-images.githubusercontent.com/14908883/41104669-94d7b7fe-6a74-11e8-9fee-2d7e4389ceb9.png)

**fixed**

**Comment by valentiay** [comment]
Страница 22. Две вертикальных черты вместо одной
![image](https://user-images.githubusercontent.com/14908883/41105854-536812fc-6a77-11e8-88ad-a09075d4e737.png)

Еще в конце скобка не того размера

**fixed**

**Comment by valentiay** [comment]
Страница 23. Пропущены скобки после `\P_\eta`
![image](https://user-images.githubusercontent.com/14908883/41107596-4fa367f8-6a7b-11e8-859b-af964a9049bc.png)

**fixed**

**Comment by valentiay** [comment]
Страница 23. Скобка у `\xi` не в ту сторону
![image](https://user-images.githubusercontent.com/14908883/41110477-24f83608-6a82-11e8-839e-78948fcbc555.png)

**fixed**

**Comment by valentiay** [comment]
Страница 25. Не хватает скобки
![image](https://user-images.githubusercontent.com/14908883/41110781-e4c7e53c-6a82-11e8-9c30-6460fac8a7bc.png)

**fixed**

**Comment by valentiay** [comment]
Страница 25. `|f(x)| \leqslant C`
![image](https://user-images.githubusercontent.com/14908883/41110928-454a1a9c-6a83-11e8-86b9-17cfee81b151.png)

**fixed**
